---
title: "Comparision"
author: "E G"
date: "3/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Comparision

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)

df <- read_excel("risk_level_updated_look_into_R.xlsx")

df_comparision <- df %>%
  select(sg_setor_r, cd_grau_ri, sector,value_natural_angle:risk_level_natural_slope_half_s )

```

### Using chi-squared to compared
```{r}
chisq.test(df_comparision$cd_grau_ri, df_comparision$risk_level_one_sd)

chisq.test(df_comparision$cd_grau_ri, df_comparision$risk_level_half_sd)

chisq.test(df_comparision$cd_grau_ri, df_comparision$risk_level_natural_slope_one_sd)

chisq.test(df_comparision$cd_grau_ri, df_comparision$risk_level_natural_slope_half_s)

```

##Plot
```{r}
ggplot(df_comparision) +
  aes(x = cd_grau_ri, fill = risk_level_one_sd) +
  geom_bar() +
  scale_fill_hue() +
  theme_minimal()

ggplot(df_comparision) +
  aes(x = cd_grau_ri, fill = risk_level_half_sd) +
  geom_bar() +
  scale_fill_hue() +
  theme_minimal()

ggplot(df_comparision) +
  aes(x = cd_grau_ri, fill = risk_level_natural_slope_one_sd) +
  geom_bar() +
  scale_fill_hue() +
  theme_minimal()

ggplot(df_comparision) +
  aes(x = cd_grau_ri, fill = risk_level_natural_slope_half_s) +
  geom_bar() +
  scale_fill_hue() +
  theme_minimal()

```

