---
title: "Functions"
author: "Erica Goto"
date: "3/11/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Functions

```{r dataset}
library(readxl)
library(dplyr)
escorregamento <- read_excel("BD-IPT 2010_todos.xls")

```

#Changing values data,frane

```{r , include=FALSE}



escorregamento[escorregamento == "alvenaria"] <- 2.792746
escorregamento[escorregamento == "madeira"] <- 0.500518114285714
escorregamento[escorregamento == "misto"] <- 3.9606216

escorregamento[escorregamento == "inex"] <- 0.0442203843843844
escorregamento[escorregamento == "precario"] <- 0.0363238871728872
escorregamento[escorregamento == "satisf"] <- 0.00719458634825302

escorregamento[escorregamento == "Dens1"] <- 0.49306412137931
escorregamento[escorregamento == "Dens2"] <- 1.50720737103448
escorregamento[escorregamento == "Dens3"] <- 2.4373056
escorregamento[escorregamento == "Dens4"] <- 1.16542428689655

escorregamento$tc_estruturas_desfav[escorregamento$tc_estruturas_desfav == 1] <- 8.328848



escorregamento$BANANEIRA[escorregamento$BANANEIRA == 1] <- 3.69775570932476
escorregamento$arvores[escorregamento$arvores == 1] <- 0.818966029581993
escorregamento$rasteiras[escorregamento$rasteiras == 1] <- 1.61311490675241
escorregamento$desmatada[escorregamento$desmatada == 1] <- 3.8590672

escorregamento$fossa[escorregamento$fossa == 1] <- 2.97587938498499
escorregamento$vazamento[escorregamento$vazamento == 1] <- 6.0424868
escorregamento$conc_agua_chuva[escorregamento$conc_agua_chuva == 1] <- 3.030316203003
escorregamento$lancamento_agua_servida[escorregamento$lancamento_agua_servida == 1] <- 5.04447846966967



escorregamento$trincas_moradia_terreno[escorregamento$trincas_moradia_terreno == 1] <- 16.35
escorregamento$inclinados[escorregamento$inclinados == 1] <- 10.6
escorregamento$degraus_abatimento[escorregamento$degraus_abatimento == 1] <- 23.7
escorregamento$cicatrizes[escorregamento$cicatrizes == 1] <- 19.8
escorregamento$embarrigados[escorregamento$embarrigados == 1] <- 13.1


escorregamento$lixo[escorregamento$lixo == 1] <- 5.0015542
escorregamento$aterro[escorregamento$aterro == 1] <- 5.0015542
escorregamento$entulho[escorregamento$entulho == 1] <- 5.0015542


# dplyr
escorregamento_ipt <- escorregamento %>%
  select("Subprefeitura:", Area, Densidade, tc_estruturas_desfav, moradia, aterro, lixo, entulho, trincas_moradia_terreno, embarrigados, cicatrizes, degraus_abatimento, inclinados, conc_agua_chuva, lancamento_agua_servida, vazamento, fossa, drenagem, arvores, rasteiras, desmatada, BANANEIRA, RISCO)

escorregamento_ipt$Densidade <- as.numeric(escorregamento_ipt$Densidade)
as.numeric(escorregamento_ipt$aterro)
as.numeric(escorregamento_ipt$lixo)
as.numeric(escorregamento_ipt$entulho)
as.numeric(escorregamento_ipt$trincas_moradia_terreno)
as.numeric(escorregamento_ipt$embarrigados)
as.numeric(escorregamento_ipt$cicatrizes)
as.numeric(escorregamento_ipt$degraus_abatimento)
as.numeric(escorregamento_ipt$conc_agua_chuva)
as.numeric(escorregamento_ipt$lancamento_agua_servida)
as.numeric(escorregamento_ipt$vazamento)
as.numeric(escorregamento_ipt$fossa)
escorregamento_ipt$drenagem<-as.numeric(escorregamento_ipt$drenagem)
as.numeric(escorregamento_ipt$arvores)
as.numeric(escorregamento_ipt$rasteiras)
as.numeric(escorregamento_ipt$desmatada)
as.numeric(escorregamento_ipt$BANANEIRA)
as.factor(escorregamento_ipt$RISCO)
as.numeric(escorregamento_ipt$tc_estrutura_desfav)
escorregamento_ipt$moradia<-as.numeric(as.character(escorregamento_ipt$moradia))
as.factor(escorregamento_ipt$moradia)

    
```

# Equation:
```{r}

escorregamento_ipt <- escorregamento_ipt %>%
  mutate(Agua = conc_agua_chuva + lancamento_agua_servida + vazamento + fossa + drenagem )

escorregamento_ipt$Agua <- ifelse(escorregamento_ipt$Agua > 6.04, 6.04, escorregamento_ipt$Agua)

escorregamento_ipt <- escorregamento_ipt %>%
    mutate(Instab = trincas_moradia_terreno + embarrigados + cicatrizes + degraus_abatimento + inclinados )

escorregamento_ipt$Instab <- ifelse(escorregamento_ipt$Instab > 5.0015542, 5.0015542, escorregamento_ipt$Instab)


escorregamento_ipt <- escorregamento_ipt %>%
  mutate(Veg = arvores + rasteiras + desmatada + BANANEIRA )

escorregamento_ipt$Veg <- ifelse(escorregamento_ipt$Veg > 3.8590672, 3.8590672, escorregamento_ipt$Veg)

escorregamento_ipt <- escorregamento_ipt %>%
  mutate(AterroLixo = lixo + aterro + entulho)

escorregamento_ipt$AterroLixo <- ifelse(escorregamento_ipt$AterroLixo > 5.0015542, 5.0015542, escorregamento_ipt$AterroLixo)


escorregamento_ipt <- escorregamento_ipt %>%
  mutate(RiscoComputado = AterroLixo + Veg + Instab + Agua + Densidade + tc_estruturas_desfav + moradia+34.2205842)




```


Data.frame with Degree of Risk and RiskComputate

```{r}

df <- escorregamento_ipt %>%
  select("Subprefeitura:", Area, RISCO, RiscoComputado)


R1 <- df %>%
  filter(RISCO == "R1") %>%
  select(RISCO:RiscoComputado)

R2 <- df %>%
  filter(RISCO == "R2") %>%
  select(RISCO:RiscoComputado)


R3 <- df %>%
  filter(RISCO == "R3") %>%
  select(RISCO:RiscoComputado)

R4 <- df %>%
  filter(RISCO == "R4") %>%
  select(RISCO:RiscoComputado)


Risco1 <-R1$RiscoComputado
Risco2 <-R2$RiscoComputado
Risco3 <-R3$RiscoComputado
Risco4 <-R4$RiscoComputado

Mean_R1 <- mean(Risco1)
SD_R1 <- sd(Risco1)

Mean_R2 <- mean(Risco2)
SD_R2 <- sd(Risco2)

Mean_R3 <- mean(Risco3)
SD_R3 <- sd(Risco3)

Mean_R4 <- mean(Risco4)
SD_R4 <- sd(Risco4)

df_risk <- data.frame(c("Risco", "R1", "R2", "R3", "R4"), 
                      c("Mean", Mean_R1, Mean_R2, Mean_R3, Mean_R4), 
                      c("SD", SD_R1, SD_R2, SD_R3, SD_R4))
df_risk
                      

```

