---
title: "Dynamic report"
params:
  a: NA
  b: NA
  c: NA
  d: NA
  e: NA
  f: NA
  g: NA
  h: NA
  i: NA
  j: NA
  k1: NA
  k2: NA
  k3: NA
  l: NA
  m: NA
  n: NA
  o: NA
  p: NA
  q: NA
  r: NA
  s: NA
  t: NA
  u: NA
  v: NA
  v1: NA
  v2: NA
  v3: NA
  v4: NA
  v5: NA
  v6: NA
  w: NA
  x: NA
  x1: NA
  x2: NA
  x3: NA
  z: NA
  y: NA
  y1: NA
  y2: NA
  y3: NA
  y4: NA
  p1: NA
  w1: NA
  w2: NA
  w3: NA
  w4: NA
  w5: NA
  w6: NA
  w7: NA
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Relatorio com respostas

```{r}
    data.frame(
      
      Caracteristica = c("Municipio", 
                         "Area",
                         "Bairro",
                         "Setor", 
                         "Equipe",
                         "Data",
                         "UA",
                        "Localizacao", 
                         "Moradores",
                        "Acesso ao local",
                         "Tipo de moradias",
                         "Observacao moradias",
                        "Densidade da ocuapacao", 
                        "Via", 
                         "Observacao da via",
                         "Tipo de encosta", 
                        "Talude de corte",
                         "Altura maxima da encosta natural",
                         "Distancia da moradia",
                        "Angulo de inclinacao" ,
                         "Posicao da  moradia",
                        "Geologia", 
                        "Solo residual",
                          "Saprolito", 
                          "Rocha alterada",
                          "Rocha sa", 
                          "Aterro",
                          "Lixo",
                          "Entulho",
                      "Lancamento de agua servida",
                      "Concentracao de agua de chuva",
                      "Vazamento",
                      "Fossa septica",
                        "Tipo de drenagem" ,
                      "Presenca de arvores",
                          "Presenca de vegetacao rasteira",
                          "Solo exposto/vegetacao desmatada",
                      "Bananeira",
                          "Cobertura urbana",
                        "Muro embarrigado", 
                         "Trinca na moradia", 
                         "Arvores, postes, e muros inclinados",
                         "Degrau de abatimento",
                         "Cicatrizes de escorregamento",
                         "Trinca no terreno"
                         ), 
      
      Resposta = as.character (c(
                        params$a,  params$b,  params$c,  params$d,  params$e,  params$f,
                         params$g,  params$h,  params$i,  params$j,  params$k,  params$l, 
                         params$m,  params$n, params$o,  params$p, params$p1,  params$q,
                        params$r, params$s, params$t,  params$u,  params$v,
                        params$v1, params$v2, params$v3, params$v4, params$v5, params$v6,
                        params$x, params$x1, params$x2, params$x3, 
                    params$z, params$y, params$y1, params$y2,params$y4, params$y3, params$w,
                         params$w1, params$w2, params$w3, params$w5, params$w6)
                              ))

              



```



