############# Reactive for excel #######################


textValues2 <- reactive({
  data.frame("Municipio" = input$txt_mun, 
             "Area" = input$txt_area, 
             "Bairro"= input$txt_bairro, 
             "Setor" = input$txt_setor,
             "Equipe" = input$txt_equip, 
             "Data" = as.character(input$date), 
             "UA" = input$select_UA, 
             "Localizacao" = input$txt_loc, 
             "Moradores contato" = input$txt_moradores, 
             "Acesso" = input$txt_acesso, 
             "Moradia alvernaria" = input$select_moradia_alvenaria,
             "Moradia madeira" = input$select_moradia_madeira,
             "Moradia mista" = input$select_moradia_mista,
             "Moradia (observacoes)" = input$txt_moradia,
             "Densidade" = input$select_densidade,
             "Via de acesso" = input$select_via, 
             "Via de acesso (observacoes)" = input$txt_via,
             "Encosta Natural" = input$select_encosta, 
             "Talude de corte" = input$select_talude,
             "Altura maxima do talude" = input$txt_h_max, 
             "Distancia Moradia" = input$txt_dist_moradia, 
             "Angulo de inclinacao" = input$select_angle, 
             "Posicao/Localiz das moradias" = input$select_posicao_moradia,
             "Geologia" = input$select_geol, 
             "Solo residual" = input$select_residual,
             "Saprolito" = input$select_saprolito, 
             "Rocha alterada" = input$select_rocha_alterada,
             "Rocha sa" = input$select_rocha_sa,
             "Aterro" = input$select_aterro,
             "Lixo" = input$select_lixo,
             "Entulho" =input$select_entulho,
             "Lançamento de água servida em superfície" = input$select_lancamento,
             "Concentração de água de chuva em superfície" = input$select_chuva,
             "Vazamento da tubulação" = input$select_vazamento,
             "Fossa septica" = input$select_fossa,
             "Drenagem" = input$select_drenag, 
             "Presença de árvores"  = input$select_arvore,
             "Vegetação rasteira/arbustiva" = input$select_rasteira,
             "área desmatada/solo exposto" = input$select_desmatado,
             "Cobertura_urbana" = input$select_urbana,
             "Muro embarrigado" = input$select_embarrigado,
             "Trinca moradia" = input$select_trinca_moradia,
             "Arvores, postes, e muros inclinados" = input$select_inclinados,
             "Degrau de abatimento" = input$select_degrau,
             "Cicatriz de escorregamento" = input$select_cicatriz,
             "Trinca no terreno" =input$select_trinca_terreno,
             "Grau de risco" = output$grau_risco)
} )


######################## end Reactive for excel ##################

